# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

############################
## Theme
############################

theme = "forest" 	     	# options: minimal, 1950s, coffee, dark, forest, strawberry, rose, ocean, mr_robot
day_night = false  			# Enable users to switch between day and night mode?
font = "Minimal"    		# options: "Rose" "Minimal" "Classic" 
font_size = "M"   			# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)

############################
## Basic Info
############################

site_type = "Person"
local_business_type = ""
org_name = ""
description = "" 
logo = "" 					# To enable, place an image in `static/img/`

############################
## Site Features
############################

# Enable source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = false
highlight_languages = ["r"]  # Add support for highlighting additional languages
# highlight_style = "github" # For supported styles, see https://cdnjs.com/libraries/highlight.js/

math = false 				# Enable LaTeX math rendering? true/false
diagram = false 			# Enable diagram rendering? true/false
privacy_pack = false

############################
## Contact details
##
## These details power the Contact widget (if enabled).
## Additionally, for organizations, these details may be used to enrich search engine results.
############################

# Enter contact details (optional). To hide a field, clear it to "".
email = "tanerumit@gmail.com"
#phone = ""
#adress = ""

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.

contact_links = [
  {icon = "envelope", icon_pack = "ai", link = "tanerumit@gmail.com"}
  #{icon = "twitter", icon_pack = "fa", link = "https://twitter.com/hydrogalactica"},
  #{icon = "skype",   icon_pack = "fa", link = "skype:echo123?call"},
  #{icon = "google-scholar", icon_pack = "ai", link = "https://scholar.google.com/citations?user=sFk6CpIAAAAJ&hl=en&oi=ao"},
  #{icon = "github", icon_pack = "fa", link = "//github.com/tanerumit/"},
  #{icon = "linkedin", icon_pack = "fa", link = "https://www.linkedin.com/in/tanerumit/"},
  #{icon = "orcid", icon_pack = "ai", link = "https://orcid.org/0000-0002-4710-6537"}
]

############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter = "hydrogalactica"

############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-us"

############################
## Advanced
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {align = "l", show_logo = true}

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Link authors to their profile page? (true/false)
link_authors = true

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js  = []

# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  de = {order = ['street', 'postcode', 'city'], delimiters = [', ', ' ', '']}
  fr-fr = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "January 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

############################
## Comments
############################
[comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  engine = 0

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true, project = true, publication = true, talk = true}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)

############################
## Search
############################
[search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

############################
## Maps
############################
[map]
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  engine = 0
  api_key = ""
  zoom = 15

############################
## Marketing
############################
[marketing]
  google_analytics = ""
  google_tag_manager = ""
